/* Auto-generated by genmsg_cpp for file /home/darobot/orb_slam/ORB_SLAM2/msg/Points.msg */
#ifndef ORB_SLAM2_MESSAGE_POINTS_H
#define ORB_SLAM2_MESSAGE_POINTS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Point.h"

namespace ORB_SLAM2
{
template <class ContainerAllocator>
struct Points_ {
  typedef Points_<ContainerAllocator> Type;

  Points_()
  : header()
  , frame_id(0.0)
  , points()
  , distances()
  {
  }

  Points_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , frame_id(0.0)
  , points(_alloc)
  , distances(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _frame_id_type;
  double frame_id;

  typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points_type;
  std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  points;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _distances_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  distances;


  typedef boost::shared_ptr< ::ORB_SLAM2::Points_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ORB_SLAM2::Points_<ContainerAllocator>  const> ConstPtr;
}; // struct Points
typedef  ::ORB_SLAM2::Points_<std::allocator<void> > Points;

typedef boost::shared_ptr< ::ORB_SLAM2::Points> PointsPtr;
typedef boost::shared_ptr< ::ORB_SLAM2::Points const> PointsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ORB_SLAM2::Points_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ORB_SLAM2::Points_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ORB_SLAM2

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::Points_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::Points_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ORB_SLAM2::Points_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dce7a600cde9b182513159993f0e4463";
  }

  static const char* value(const  ::ORB_SLAM2::Points_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdce7a600cde9b182ULL;
  static const uint64_t static_value2 = 0x513159993f0e4463ULL;
};

template<class ContainerAllocator>
struct DataType< ::ORB_SLAM2::Points_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ORB_SLAM2/Points";
  }

  static const char* value(const  ::ORB_SLAM2::Points_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ORB_SLAM2::Points_<ContainerAllocator> > {
  static const char* value() 
  {
    return "std_msgs/Header header\n\
\n\
float64 frame_id\n\
geometry_msgs/Point[] points\n\
float64[] distances\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::ORB_SLAM2::Points_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::ORB_SLAM2::Points_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::ORB_SLAM2::Points_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ORB_SLAM2::Points_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.frame_id);
    stream.next(m.points);
    stream.next(m.distances);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Points_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ORB_SLAM2::Points_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ORB_SLAM2::Points_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frame_id: ";
    Printer<double>::stream(s, indent + "  ", v.frame_id);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "distances[]" << std::endl;
    for (size_t i = 0; i < v.distances.size(); ++i)
    {
      s << indent << "  distances[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.distances[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ORB_SLAM2_MESSAGE_POINTS_H

